name: Docs Deploy

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'doc/gen-cli-ref/**'
      - 'README.md'
      - 'pkg/diffyml/cli/cli.go'
      - 'pkg/diffyml/cli/flag_metadata.go'
      - '.diffyml.yml.example'
      - '.github/workflows/docs-deploy.yml'
      - '.github/workflows/_docs-build.yml'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/_docs-build.yml
    with:
      upload-artifact: true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0
      - id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
